### ISSUE TITLE
LDproxy: some SNPs are lost

### ISSUE THREAD

**Issue by PlatonB** [CBIIT/nci-webtools-dceg-linkage#55]
I.
1. LDPair
2. **rs9268765** and _rs9268796_, EUR
D': 1.0, R2: 1.0
3. **rs9268765** and _rs6457589_, EUR
D': 1.0, R2: 1.0

II.
1. LDproxy
2. **rs9268765**, EUR
3. Download all proxy variants
4. CTRL+F, _rs9268796_
5. CTRL+F, _rs6457589_

Result.
_rs9268796_ and _rs6457589_ are in the strongest LD with **rs9268765**, but not included into LDproxy's output.

**Comment by kvnjng** [comment]
Hi @PlatonB ,
 
It looks like **rs9268796** and **rs6457589** _do_ show up in the LDproxy output file but can only be found by their chromosome:positions (**chr6:32421329** and **chr6:32419961**). 

<img width="852" alt="Screen Shot 2019-04-24 at 10 37 42 AM" src="https://user-images.githubusercontent.com/21976531/56675494-31e32300-668a-11e9-9b8e-d92b9595b9bb.png">

Their rsnums are represented by a single dot (“.”) as a result from the 1000G v5 files LDLink uses (ALL.chr<#>.phase3_shapeit2_mvncall_integrated_v5.20130502.genotypes.vcf.gz). For some variants queried by their chromosome:position via tabix, a single dot (“.”) appears in the second column instead of where the rsnum is supposed to be listed. 
 
I ran the same tabix queries of these to chromosome:positions of interest on the newer 1000G **v5a** chromosome 6 file but received rs567082101 and rs561689382 instead.
 
After checking https://api.ncbi.nlm.nih.gov/variation/v0/#/RefSNP/get_beta_refsnp__rsid_ , it appears that rs567082101 merges into rs9268796 and rs561689382 merges into rs6457589.
